const strings = {
    name: 'name',
    email: 'email',
    login: 'Login',
    username: 'username',
    password: 'password',
    update: 'update',
    create: 'create',
    title: 'title',
    description: 'description',
    members: 'members',
    create_member: 'create member',
    create_task: 'create task',
    check: 'check',
    tasks: 'tasks',
    dashboard: 'Dashboard',
    please_fill_name_field: "Please fill the name input",
    please_fill_title: "Please fill the title input",
    please_fill_all_fields: "Please fill all fields",
    are_you_sure_you_want_to_delete: 'Are you sure you want to delete?',
}
export default strings